/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gpio_api_GpioUtils */

#ifndef _Included_com_android_gpio_api_GpioUtils
#define _Included_com_android_gpio_api_GpioUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_gpio_api_GpioUtils
 * Method:    NativeGpioOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_gpio_1api_GpioUtils_NativeGpioOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_gpio_api_GpioUtils
 * Method:    NativeGpioIoctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_gpio_1api_GpioUtils_NativeGpioIoctl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_gpio_api_GpioUtils
 * Method:    NativeGpioClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gpio_1api_GpioUtils_NativeGpioClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
