/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_uart_api_UartUtils */

#ifndef _Included_com_android_uart_api_UartUtils
#define _Included_com_android_uart_api_UartUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_uart_api_UartUtils
 * Method:    UartOpen
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_android_uart_1api_UartUtils_UartOpen
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_android_uart_api_UartUtils
 * Method:    UartClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_uart_1api_UartUtils_UartClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
