/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_net_api_NetUtils */

#ifndef _Included_com_android_net_api_NetUtils
#define _Included_com_android_net_api_NetUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_net_api_NetUtils
 * Method:    NativeNetOpen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_android_net_1api_NetUtils_NativeNetOpen
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_android_net_api_NetUtils
 * Method:    NativeNetClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_net_1api_NetUtils_NativeNetClose
  (JNIEnv *, jclass);

/*
 * Class:     com_android_net_api_NetUtils
 * Method:    NativeNetRead
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_net_1api_NetUtils_NativeNetRead
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_android_net_api_NetUtils
 * Method:    NativeNetWrite
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_net_1api_NetUtils_NativeNetWrite
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
