/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_fan_api_FanUtils */

#ifndef _Included_com_android_fan_api_FanUtils
#define _Included_com_android_fan_api_FanUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_fan_api_FanUtils
 * Method:    NativeFanOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_fan_1api_FanUtils_NativeFanOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_fan_api_FanUtils
 * Method:    NativeFanIoctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_fan_1api_FanUtils_NativeFanIoctl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_fan_api_FanUtils
 * Method:    NativeFanClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_fan_1api_FanUtils_NativeFanClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
