/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_spi_api_SpiUtils */

#ifndef _Included_com_android_spi_api_SpiUtils
#define _Included_com_android_spi_api_SpiUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_spi_api_SpiUtils
 * Method:    NativeSpiOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_spi_1api_SpiUtils_NativeSpiOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_spi_api_SpiUtils
 * Method:    NativeSpiClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_spi_1api_SpiUtils_NativeSpiClose
  (JNIEnv *, jclass);

/*
 * Class:     com_android_spi_api_SpiUtils
 * Method:    NativeSpiRead
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_spi_1api_SpiUtils_NativeSpiRead
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_android_spi_api_SpiUtils
 * Method:    NativeSpiWrite
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_spi_1api_SpiUtils_NativeSpiWrite
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_android_spi_api_SpiUtils
 * Method:    NativeSpiIoctl
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_android_spi_1api_SpiUtils_NativeSpiIoctl
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
